dashpay/dash-evo-tool

src/context.rs
src/database/identities.rs
src/model/qualified_identity.rs
src/platform/identity/load_identity.rs
src/platform/identity/register_identity.rs
src/ui/dpns_contested_names_screen.rs

Before, we were excluding names that were never contested! ☹️

feat: get all owned dpns names

---

src/ui/identities/top_up_identity_screen/mod.rs

If the user clicked max amount at any time, the funding_amount_exact would be set to that amount and it would never be overwritten, even if they changed the input amount

fix: custom top up amount from wallet balance

---

Cargo.toml

Edit Cargo.toml with latest commit of test/testWithoutSpan2

feat: update platform with sdk error deserialization

---

src/ui/wallets/wallets_screen/mod.rs

feat: clean up wallet screen

---

src/sdk_wrapper.rs
src/ui/components/wallet_unlock.rs
src/ui/identities/add_existing_identity_screen.rs
src/ui/identities/identities_screen.rs
src/ui/identities/keys/add_key_screen.rs
src/ui/identities/transfers/mod.rs

Clean up more UI. Multiple screens improved.

feat: clean up more screens

---

src/ui/identities/keys/key_info_screen.rs

feat: clean up add key screen

---

src/backend_task/tokens/mod.rs
src/ui/tokens/tokens_screen.rs

- Add token description user input field
- Allow both perpetual and preprogrammed distributions at the same time
- Allow for multiple token names with language selection
- Fix visibility of token creator error messages and "registering token..." spinner

feat: token creator updates

---

Cargo.lock
Cargo.toml
src/ui/mod.rs
src/ui/tokens/tokens_screen.rs
src/ui/tokens/view_token_claims_screen.rs

feat: token claims history screen

---

Cargo.lock
Cargo.toml
src/model/qualified_identity/mod.rs
src/ui/contracts_documents/create_document_screen.rs

- Update platform version with the proof fix
- Handle BackendTaskSuccessResult
- Add button to create another document after success

feat: create document screen improvements

---

src/backend_task/tokens/mod.rs
src/backend_task/tokens/update_token_config.rs
src/context.rs
src/database/contracts.rs
src/database/identities.rs
src/ui/contracts_documents/create_document_screen.rs
src/ui/mod.rs
src/ui/tokens/mod.rs
src/ui/tokens/tokens_screen.rs
src/ui/tokens/update_token_config.rs

Add a screen for Token Config Updates

feat: token config updates

---

src/backend_task/tokens/mod.rs
src/ui/tokens/tokens_screen.rs

Allows plural input for token names.

feat: add plural input for token names

---

src/config.rs
src/context.rs
src/ui/components/left_panel.rs

Allow users to specify in .env if they want dev mode activated for certain networks

feat: enable dev mode

---

src/context.rs
src/database/identities.rs
src/model/qualified_identity/mod.rs
src/ui/tokens/tokens_screen.rs

- Added a new method `load_local_qualified_identities_in_wallets` in `AppContext` to fetch all local qualified identities associated with wallets from the database.
- Implemented `get_local_qualified_identities_in_wallets` in the `Database` struct to handle the SQL query and data retrieval.
- Updated the `TokensScreen` to use the new method for loading identities instead of the previous method.
- Introduced a new method `available_authentication_keys_with_critical_or_high_security_level` in `QualifiedIdentity` to filter authentication keys by security level.
This change improves the functionality by allowing the application to retrieve identities more efficiently and with better categorization based on wallet associations.

feat: add function to load local qualified identities in wallets

---

Cargo.lock
Cargo.toml
src/ui/tokens/burn_tokens_screen.rs
src/ui/tokens/claim_tokens_screen.rs
src/ui/tokens/destroy_frozen_funds_screen.rs
src/ui/tokens/freeze_tokens_screen.rs
src/ui/tokens/mint_tokens_screen.rs
src/ui/tokens/pause_tokens_screen.rs
src/ui/tokens/resume_tokens_screen.rs
src/ui/tokens/unfreeze_tokens_screen.rs

- Added `humantime` crate as a dependency to format durations in a human-readable way.
- Enhanced the token distribution screens to provide detailed information about claim limitations and distribution types, including fixed, random, stepwise, linear, polynomial, exponential, logarithmic, and inverted logarithmic functions.
- Updated various screens to ensure consistent developer mode checks.
This update improves user understanding of token distribution mechanics and enhances the overall user interface experience.

feat: add humantime dependency and enhance token distribution information

---

src/database/wallet.rs
src/ui/contracts_documents/contracts_documents_screen.rs

- Added error handling for address loading in the `Database` implementation to skip rows with errors.
- Corrected a typo in the documentation comment for the `check_address_for_network` function.
- Removed unused imports in the `contracts_documents_screen.rs` file to clean up the code.

fix: handle errors in address loading

---

Cargo.lock
Cargo.toml
src/backend_task/contract.rs
src/backend_task/mod.rs
src/backend_task/register_contract.rs
src/backend_task/tokens/mod.rs
src/backend_task/tokens/query_token_non_claimed_perpetual_distribution_rewards.rs
src/backend_task/update_data_contract.rs
src/context.rs
src/database/contracts.rs
src/database/identities.rs
src/ui/contracts_documents/contracts_documents_screen.rs
src/ui/contracts_documents/mod.rs
src/ui/contracts_documents/register_contract_screen.rs
src/ui/contracts_documents/update_contract_screen.rs
src/ui/mod.rs
src/ui/tokens/tokens_screen.rs

feat: contract updates

---

src/ui/tokens/update_token_config.rs

This update introduces functionality to edit token configuration conventions directly within the UI. Users can now paste replacement JSON for token conventions, with validation for JSON format. Additionally, a "Reset to Current" button has been added to revert changes back to the current configuration. Error messages are displayed for invalid JSON input, enhancing user experience during token configuration updates.

feat: enable text editing for token configuration conventions

---

src/ui/tokens/tokens_screen.rs

Updated the `ChangeControlRulesUI` to dynamically handle groups in the user interface. The changes include:
- Added `current_groups` parameter to various rendering functions to display group options.
- Removed unused fields related to authorized groups and admin groups.
- Adjusted UI elements to show a message when no groups are available.
- Updated the logic to allow selection of groups based on their positions.
- Refactored group handling to improve clarity and maintainability.
This update enhances the user experience by allowing for dynamic interaction with groups in the change control rules.

feat: enhance ChangeControlRulesUI to handle groups dynamically

---

src/app.rs
src/backend_task/register_contract.rs
src/backend_task/update_data_contract.rs
src/ui/contracts_documents/update_contract_screen.rs
src/ui/identities/add_new_identity_screen/by_wallet_qr_code.rs
src/ui/identities/transfer_screen.rs
src/ui/identities/withdraw_screen.rs
src/ui/mod.rs
src/ui/network_chooser_screen.rs
src/ui/tokens/claim_tokens_screen.rs
src/ui/tokens/direct_token_purchase_screen.rs
src/ui/tokens/transfer_tokens_screen.rs
src/ui/tokens/unfreeze_tokens_screen.rs
src/ui/tokens/update_token_config.rs
src/ui/tools/contract_visualizer_screen.rs
src/ui/tools/mod.rs

This PR fixes the wallet creation functionality when using a QR code. The changes ensure that the process works as intended, addressing user feedback regarding failures in this area. No other modifications are included in this update.

fix: resolve wallet creation issue with QR code

---

Cargo.lock
Cargo.toml
src/backend_task/tokens/query_token_non_claimed_perpetual_distribution_rewards.rs
src/database/tokens.rs
src/ui/tokens/burn_tokens_screen.rs
src/ui/tokens/claim_tokens_screen.rs
src/ui/tokens/destroy_frozen_funds_screen.rs
src/ui/tokens/freeze_tokens_screen.rs
src/ui/tokens/pause_tokens_screen.rs
src/ui/tokens/resume_tokens_screen.rs
src/ui/tokens/tokens_screen.rs
src/ui/tokens/unfreeze_tokens_screen.rs

Updated the project dependencies to version 2.0.0-rc.14 across all relevant files. This includes changes in the `Cargo.lock` and `Cargo.toml` files to reflect the new versioning and source references for the `dapi-grpc`, `dapi-grpc-macros`, `dash-sdk`, and other related packages. 
Additionally, refactored the code to utilize a new method for validating perpetual distribution recipients in the `query_token_non_claimed_perpetual_distribution_rewards.rs` file, enhancing the overall structure and functionality of the token distribution logic. The UI components were adjusted to streamline the retrieval of data contracts, improving the efficiency of token-related operations.

chore: update dependencies to version 2.0.0-rc.14

---

src/backend_task/tokens/query_token_non_claimed_perpetual_distribution_rewards.rs
src/database/tokens.rs
src/ui/tokens/claim_tokens_screen.rs
src/ui/tokens/tokens_screen/mod.rs
src/ui/tokens/tokens_screen/render_token_details.rs

- Refactored the `validate_perpetual_distribution_recipient` function to improve parameter formatting and readability.
- Updated the `render_token_details` function to enhance the UI structure and reduce code duplication.
- Moved the `render_token_details` function to a new file for better organization.
- Adjusted various UI elements for improved layout and interaction, including button placements and label formatting.
- Removed unnecessary comments and cleaned up the code to streamline functionality. 
These changes aim to enhance the maintainability of the code and improve the user experience in the token management interface.

refactor: improve token validation and UI structure

---

src/app_dir.rs
src/backend_task/register_contract.rs
src/backend_task/tokens/query_token_non_claimed_perpetual_distribution_rewards.rs
src/context.rs
src/database/asset_lock_transaction.rs
src/database/contested_names.rs
src/database/contracts.rs
src/database/identities.rs
src/database/scheduled_votes.rs
src/database/tokens.rs
src/ui/mod.rs
src/ui/tokens/claim_tokens_screen.rs
src/ui/tokens/tokens_screen/mod.rs
src/ui/tokens/tokens_screen/my_tokens.rs
src/ui/tokens/tokens_screen/structs.rs
src/ui/tokens/update_token_config.rs
src/ui/tokens/view_token_claims_screen.rs

- Replaced `IdentityTokenBalance` with `IdentityTokenBalanceWithActions` to encapsulate available actions for each token balance.
- Introduced `IdentityTokenBasicInfo` to hold basic information about tokens without balance details.
- Updated various screens and components to utilize the new token structures, ensuring that action availability is now part of the token balance logic.
- Refactored methods to accommodate the new structures and improve overall token management in the application.

refactor: update token structure to include action availability

---

src/context.rs
src/ui/contracts_documents/document_action_screen.rs
src/ui/contracts_documents/register_contract_screen.rs
src/ui/contracts_documents/update_contract_screen.rs
src/ui/helpers.rs
src/ui/identities/keys/add_key_screen.rs
src/ui/identities/register_dpns_name_screen.rs
src/ui/identities/transfer_screen.rs
src/ui/identities/withdraw_screen.rs
src/ui/mod.rs
src/ui/tokens/burn_tokens_screen.rs
src/ui/tokens/claim_tokens_screen.rs
src/ui/tokens/destroy_frozen_funds_screen.rs
src/ui/tokens/direct_token_purchase_screen.rs
src/ui/tokens/freeze_tokens_screen.rs
src/ui/tokens/mint_tokens_screen.rs
src/ui/tokens/pause_tokens_screen.rs
src/ui/tokens/resume_tokens_screen.rs
src/ui/tokens/set_token_price_screen.rs
src/ui/tokens/tokens_screen/token_creator.rs
src/ui/tokens/transfer_tokens_screen.rs
src/ui/tokens/unfreeze_tokens_screen.rs
src/ui/tokens/update_token_config.rs

Use identity key chooser helper instead of custom chooser for each screen

refactor: use identity key chooser helper instead of custom chooser for each screen

---

src/backend_task/contract.rs
src/database/contracts.rs
src/ui/tokens/add_token_by_id_screen.rs
src/ui/tokens/tokens_screen/contract_details.rs
src/ui/tokens/tokens_screen/keyword_search.rs
src/ui/tokens/tokens_screen/mod.rs
src/ui/tokens/tokens_screen/token_creator.rs

- UI improvements
- Added a View Schema button for tokens in the Contract Details screen
- Display singular name instead of plural
- Mark required fields for token creator with *
- Add loading screen when fetching contract details
- Add clear button in keyword search

feat: keyword search improvements

---

Cargo.lock
Cargo.toml
src/backend_task/document.rs
src/backend_task/identity/register_dpns_name.rs
src/backend_task/tokens/burn_tokens.rs
src/backend_task/tokens/claim_tokens.rs
src/backend_task/tokens/destroy_frozen_funds.rs
src/backend_task/tokens/freeze_tokens.rs
src/backend_task/tokens/mint_tokens.rs
src/backend_task/tokens/pause_tokens.rs
src/backend_task/tokens/purchase_tokens.rs
src/backend_task/tokens/resume_tokens.rs
src/backend_task/tokens/set_token_price.rs
src/backend_task/tokens/transfer_tokens.rs
src/backend_task/tokens/unfreeze_tokens.rs
src/backend_task/tokens/update_token_config.rs
src/ui/components/contract_chooser_panel.rs
src/ui/contracts_documents/add_contracts_screen.rs
src/ui/contracts_documents/document_action_screen.rs
src/ui/tokens/mint_tokens_screen.rs

Updating to new sdk methods in Platform

feat: update sdk methods

---

src/backend_task/tokens/update_token_config.rs
src/ui/contracts_documents/group_actions_screen.rs
src/ui/tokens/tokens_screen/my_tokens.rs
src/ui/tokens/update_token_config.rs

Fixes an issue where token update action screen doesn't contain required information.
This pull request introduces logging improvements, refactors the handling of `TokenEvent` in `GroupActionsScreen`, and simplifies the codebase by replacing match statements with dedicated methods. The changes enhance code readability, maintainability, and debugging capabilities.
* Added a `tracing::trace!` statement in `update_token_config.rs` to log details about `group_info`, `identity_token_info`, and `change_item` during token configuration updates.
* Replaced the large match statement for `TokenEvent` in `GroupActionsScreen` with dedicated methods (`get_token_event_type`, `get_token_event_info`, and `get_token_event_note`) to improve readability and maintainability. …

refactor: simplify token config update group action

---

src/ui/wallets/wallets_screen/mod.rs

Added wallet unlock to wallet screen so users can unlock and then add receiving address. Also just makes sense to allow unlock from wallet screen.

feat: wallet unlock on wallet screen

---

src/ui/helpers.rs
src/ui/identities/keys/key_info_screen.rs

Keys weren't displaying the key type in the selector.

feat: better display in key selector

---

src/ui/components/contract_chooser_panel.rs
src/ui/dpns/dpns_contested_names_screen.rs
src/ui/identities/keys/key_info_screen.rs

Do +/- buttons instead of the dropdown arrows, and other UI improvements

feat: nicer contract chooser panel

---

src/ui/tokens/tokens_screen/distributions.rs
src/ui/tokens/tokens_screen/groups.rs
src/ui/tokens/tokens_screen/mod.rs
src/ui/tokens/tokens_screen/token_creator.rs

feat: nicer expanding tabs in token creator
