src/database/contested_names.rs, src/platform/contested_names/query_dpns_contested_resources.rs, src/ui/identities/register_dpns_name_screen.rs
The function `insert_name_contests_as_normalized_names` was returning only names that have not been updated for over an hour, and these names were being used to update the UI showing the contest states. But on testnet, contests only last one hour. So the votes for those names were not being displayed. So instead, we check the network and if it's testnet, we only update the contests created in the past hour, and on mainnet, created in the past two weeks.
Also, in registering dpns names, display aliases instead of identifiers.
=> fix: active contest vote tallies were not being updated with refresh button

src/app_dir.rs
To cover both dev environment and release cases, application should copy `.env` or `.env.example` from executable directory.
In case of release, `.env.example` is [copied](https://github.com/dashpay/dash-evo-tool/blob/v0.2-dev/.github/workflows/release.yml#L70) as `.env`
=> fix: copy .env or .env.example

src/ui/dpns_contested_names_screen.rs
I made a boo-boo and was rendering both tables for the case where we own DPNS names and also don't own any DPNS names, and it also affected the Refresh button on the Active Contests subscreen
=> fix: dpns screen rendering

src/app_dir.rs
Rename app dir to "Dash-Evo-Tool" to match qguix auto-generated dir.
=> feat: rename app dir to match eguix auto-generated dir

src/ui/dpns_contested_names_screen.rs
Refresh button when no contested names are found wasn't working
=> fix: refresh on click contested names

src/ui/components/left_panel.rs
Disable Withdrawal screen by hiding the withdrawal button
=> feat: disable withdrawal button

Cargo.toml, src/backend_task/contested_names/query_dpns_contested_resources.rs, src/database/contested_names.rs, src/database/proof_log.rs, src/model/proof_log_item.rs, src/ui/dpns_contested_names_screen.rs, src/ui/tool_screens/proof_log_screen.rs
There was an issue with proofs because we were asking for an unlimited amount of names, but we were only getting back 100. This is fixed.
=> fix: dpns names for proof error passed 100 results

Cargo.toml, src/database/identities.rs, src/ui/identities/identities_screen.rs, src/ui/identities/withdraw_from_identity_screen.rs
Max Withdrawal should now work.
Changing alias name should now persist.
Updated to v0.3
=> fix: v0.3 smaller fixes

src/components/core_zmq_listener.rs
=> chore: rename ZMQ log

src/ui/dpns_contested_names_screen.rs
If it's been less than a minute since last updating the names, just say "now" instead of seeing the seconds increasing.
=> feat: dont display seconds in dpns screen last updated column

src/backend_task/contested_names/query_dpns_contested_resources.rs, src/backend_task/contested_names/query_ending_times.rs, src/logging.rs
Limit the queries for DPNS contest ending times to 100 results per query so we don't get errors.
Also, take end time queries and contender queries outside of the resources query loop so we don't keep repeating them.
=> fix: limit 100 in dpns end time query

src/components/core_zmq_listener.rs, src/ui/components/top_panel.rs
Applied only for Windows:
- Restored ZMQ connection indicator for Windows
- Simulates socket heartbeat for ZMQ by:
- considering disconnected if no new message is received within 30 seconds. Normally, islocks are received within this time in Mainnet.
- considering connected as soon as a new message is received .
=> feat: simulate heartbeat for windows zmq

src/ui/identities/register_dpns_name_screen.rs
I had fixed this a few days ago but it got overwritten somehow.
Load the correct wallet when opening the screen for registering dpns name.
The wallet that the screen wants to unlock doesn't always align with the first identity in the identity selector.
=> fix: load the correct wallet in screen for register dpns name

src/backend_task/identity/mod.rs, src/backend_task/identity/refresh_loaded_identities_dpns_names.rs, src/ui/dpns_contested_names_screen.rs
Refresh button wasn't actually refreshing owned DPNS names on that DPNS subscreen. It was just doing a contested resource query for the other subscreens.
Also made it so that self.refreshing is set to false if the screen changes. Otherwise, the refresh button can get stuck in a Refreshing state.
=> fix: refresh owned dpns names

src/model/qualified_identity/mod.rs
The old error message printed the entire IdentityPublicKey and the entire QualifiedIdentity
This error message was huge - like 50,000 chars for my identity that has a bunch of keys.
So I changed the error message to look like this `Error: Protocol error: Generic Error: Key 1 (AUTHENTICATION) not found in identity "JBxLb52DKv2BHwdg7zf2tM84qKUfXqoEu1fQw3zKYQyY"`
=> fix: key not found error message

src/ui/dpns_vote_scheduling_screen.rs
We were sorting backend messages by message type, but we also need to filter the message content to prevent messages from other screens triggering events on this screen. Really, we need to do this on every screen and probably come up with a better system for it. I view this as more of a quick patch-up
=> fix: filter messages in vote scheduling screen

src/ui/components/wallet_unlock.rs, src/ui/identities/top_up_identity_screen/by_using_unused_asset_lock.rs, src/ui/identities/top_up_identity_screen/by_using_unused_balance.rs, src/ui/identities/top_up_identity_screen/by_wallet_qr_code.rs, src/ui/identities/top_up_identity_screen/mod.rs
The Top Up Screen flow didn't make sense since we would ask which loaded wallet to use to top up with even though the top up method might not require any loaded wallet. So I fixed the flow to only ask for loaded wallet if necessary, and also cleaned up with UI.
=> feat: clean up top up screen

src/main.rs
Force egui to store its config file in app dir (and stop creating directories Dash-Evo-Tool-v<version>)
=> fix: store egui config in app dir

src/backend_task/broadcast_state_transition.rs, src/backend_task/mod.rs, src/ui/tools/transition_visualizer_screen.rs
Add button for broadcasting decoded state transitions in the Tools screen. Cleaned up the whole subscreen too.
=> feat: broadcast decoded state transitions

src/ui/identities/mod.rs, src/ui/identities/register_dpns_name_screen.rs, src/ui/identities/transfers/mod.rs, src/ui/identities/withdraw_from_identity_screen.rs
Wallet unlock wasn't being rendered upon opening the withdrawal screen.
Also, transfer screen was using the wrong key for signing because it called "get_selected_key" which returned the key for signing DPNS domain documents. So I fixed that function and made it usable across multiple screens.
=> fix: wallet unlock rendering

src/database/identities.rs, src/ui/identities/identities_screen.rs
Users now have greater control over ordering of identities in the identities screen.
Added clickable column headers that will toggle sort asc/desc as well as up and down arrows for each identity.
The ordering is saved in the database as well so that upon app restart, the ordering is the same as how the user left it.
=> feat: identity ordering

src/ui/identities/transfers/mod.rs
If there's an error, close the confirmation pop-up.
Also, only submit transfer on button click rather than pressing enter, since the "enter" from wallet unlock was triggering it.
=> fix: improper confirmation pop-up rendering on transfer screen

src/ui/identities/identities_screen.rs
The order of identities was not saving when they were sorted - only when a custom order was being used with the up/down arrows.
=> fix: identity order not saving on sort

Cargo.toml
Bug where users couldn't withdraw with owner key was fixed.
=> feat: update platform revision with withdrawal fix

src/backend_task/identity/mod.rs, src/ui/identities/identities_screen.rs
If there was an error refreshing identities, the screen's refreshing status wasn't being set to false.
=> fix: handle identity refresh errors

src/database/identities.rs, src/ui/identities/identities_screen.rs
Includes a fix for an issue that was causing some apps to panic on startup. If a user had moved their identities around in the identities screen (they were using a custom order) and then removed an identity, the identity would be removed from identity table in database but not identity_order, and it would cause a panic when loading the order.
To fix, we do 3 things:
1) add a foreign key to identity_order table so that deletions in identity table also delete in identity_order table
2) add a check in load_identity_order that deletes identities from identity_order table if they are present in identity_order but not identity table
3) when ordering the identities in identities screen, if an identity is in the order table but not in the identity table, ignore it
=> v0.8.1-dev to master

src/backend_task/tokens/mod.rs
Just copied the token description defined in the token creator over to the contract description as well.
=> fix: keyword search not working with token creator tokens

.gitignore
This pull request updates the `.gitignore` file to include `explorer.log` in the list of ignored files. This change ensures that any log files generated by the explorer tool are not tracked by Git, keeping the repository clean and free from unnecessary log files.
- Added `explorer.log` to the `.gitignore` file.  
- This helps prevent clutter in the repository and avoids accidentally committing log files generated during development or testing.
Ignoring log files is a common practice to maintain a clean codebase and to ensure that only relevant files are tracked in the version control system.
=> chore: update .gitignore to exclude explorer.log

src/ui/tokens/tokens_screen.rs
This update introduces a validation mechanism for contract keywords entered in the tokens screen. The keywords are now checked to ensure they are between 3 and 50 characters long.
Previously, there was no validation for the length of contract keywords, which could lead to issues with overly short or excessively long entries. This change ensures that only valid keywords are processed, improving the robustness and reliability of the application.
- Users will receive an error message if they attempt to enter a keyword that does not meet the length requirements.
- This change ensures better data integrity and prevents potential issues related to invalid keyword lengths.
=> fix: add validation for contract keyword length

src/main.rs
This pull request adds support for a variety of new fonts and languages in the application. The changes include integrating additional fonts into both the default and monospace font families, enhancing the application's ability to render text in multiple languages and incorporate emojis.
- Added new font entries such as `emoji-icon-font`, `NotoEmoji-Regular`, and various `noto_sans` fonts for different languages (e.g., Simplified Chinese, Traditional Chinese, Japanese, Korean, Thai, Khmer, Arabic, Hebrew, and Devanagari) to the default font family.
- Updated the monospace font family with the same set of fonts to ensure consistent rendering across different text styles.
These changes are intended to improve the user experience by supporting a wider range of languages and emojis, …
=> feat: add support for additional fonts and languages

Cargo.lock, Cargo.toml, src/ui/tokens/tokens_screen.rs
This pull request introduces the `enum-iterator` crate to the project, which simplifies the management of enumerations, specifically for the `TokenNameLanguage` enum.
- Added `enum-iterator` and `enum-iterator-derive` to `Cargo.toml` and `Cargo.lock`.
- Implemented the `Sequence` trait from `enum-iterator` for the `TokenNameLanguage` enum.
- Updated the logic in `TokensScreen` to utilize `enum-iterator` for iterating over `TokenNameLanguage` values and selecting the next unused language.
By using `enum-iterator`, we can easily iterate over all possible values of an enum, which is particularly useful for selecting the next available language in the token name input feature. This change enhances code readability and reduces the potential for errors when managing enum variants.
=> feat: integrate enum-iterator to manage token name languages

src/ui/identities/add_new_identity_screen/mod.rs
Updated the security levels for authentication keys in the AddNewIdentityScreen module. Changed the security level from HIGH to CRITICAL for certain keys to enhance security. Additionally, added new key handling for authentication with a security level of HIGH where appropriate. This change improves the overall security posture of the identity management system.
=> fix: update security levels for authentication keys

src/context.rs, src/database/identities.rs, src/model/qualified_identity/qualified_identity_public_key.rs
- Updated `get_identity_by_id` to accept a reference to wallets for improved identity fetching.
- Modified the SQL query to include a condition for local identities and non-null data.
- Added logic to associate wallets with identities and retrieve top-ups for each identity.
- Enhanced `QualifiedIdentityPublicKey` to check for valid public keys only if the data length exceeds 20 bytes. 
These changes improve the efficiency of fetching identities and ensure that wallet associations and top-ups are correctly handled.
=> feat: enhance identity fetching with wallet associations and top-ups

src/ui/tokens/burn_tokens_screen.rs, src/ui/tokens/destroy_frozen_funds_screen.rs, src/ui/tokens/freeze_tokens_screen.rs, src/ui/tokens/mint_tokens_screen.rs, src/ui/tokens/pause_tokens_screen.rs, src/ui/tokens/resume_tokens_screen.rs, src/ui/tokens/transfer_tokens_screen.rs, src/ui/tokens/unfreeze_tokens_screen.rs
Updated the UI to display additional information about public keys in developer mode. The key display now includes the key ID, purpose, security level, and key type. Keys marked with critical security levels are highlighted, while others are displayed in red. The logic for displaying available authentication keys has also been modified to only show keys with critical security levels. This improves the usability and clarity of key selection for developers.
=> feat: enhance key display in developer mode

src/backend_task/identity/refresh_identity.rs, src/model/qualified_identity/qualified_identity_public_key.rs, src/ui/identities/add_existing_identity_screen.rs, src/ui/tokens/claim_tokens_screen.rs, src/ui/tokens/tokens_screen.rs
- Updated the identity refresh logic to use `update_local_qualified_identity` instead of `insert_local_qualified_identity`.
- Enhanced `QualifiedIdentityPublicKey` to support both `ECDSA_SECP256K1` and `ECDSA_HASH160` key types, including testnet address handling.
- Removed unused `identity_load_method` from `AddExistingIdentityScreen`.
- Simplified identity loading in `TokensScreen` to filter out identities without private keys.
- Added `estimate_registration_cost` method to calculate the fees for token registration based on various parameters.
- Included user feedback for estimated registration costs in the token creation confirmation popup.
- Added validation for token name lengths to ensure they meet specified criteria.
=> feat: improve identity handling and registration cost estimation

src/ui/tokens/tokens_screen.rs
The whole Searchable token name thing was very confusing. Gave the checkbox a new label and also checked for duplicate keywords and displayed error.
=> fix: show error if duplicate contract keywords in creator

Cargo.lock, Cargo.toml, src/backend_task/tokens/update_token_config.rs, src/ui/tokens/tokens_screen.rs
Updated the member selector in the token screen for groups to enhance usability. The selector now displays a combo box for identity selection, allowing users to choose from existing identities while preventing duplicates unless in developer mode. Additionally, a warning is shown if a selected identity is already used by another member in the group. This improves the user experience by making it easier to manage identities within groups. 
The `Cargo.lock` and `Cargo.toml` files were also updated to reflect the new version of the `dash-sdk` dependency, ensuring compatibility with the latest changes.
=> feat: improve member selector in token screen for groups

src/ui/contracts_documents/group_actions_screen.rs, src/ui/tokens/burn_tokens_screen.rs, src/ui/tokens/destroy_frozen_funds_screen.rs, src/ui/tokens/freeze_tokens_screen.rs, src/ui/tokens/mint_tokens_screen.rs, src/ui/tokens/pause_tokens_screen.rs, src/ui/tokens/resume_tokens_screen.rs, src/ui/tokens/set_token_price_screen.rs, src/ui/tokens/unfreeze_tokens_screen.rs, src/ui/tokens/update_token_config.rs
- Things like saying "Group Mint Initiated" instead of "Mint Successful" when necessary
- Allow navigation to Group Actions screen after initiating an Action, allow navigation to Tokens screen after signing a Group Action
- Add ChangePrice to Group Actions Screen
- Pass PublicNote from Group Actions Screen to Token Action Screen
=> feat: token screens ui improvements around group actions

Cargo.lock, Cargo.toml, src/app.rs, src/ui/network_chooser_screen.rs
This pull request introduces several enhancements to improve the handling of `dash-qt` executable paths and database settings, as well as refactoring for better code maintainability. The most important changes include adding the `which` crate for locating executables, modifying the logic for determining default `dash-qt` paths, and refactoring repeated database update calls into a new `save` method.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R55): Added the `which` crate (`version = "7.0.3"`) to enable system PATH searches for executables.
* [`src/app.rs`](diffhunk://#diff-0b979b6de560b29c1d97336878db56179224aa21d96fe099630c6628479ed020L191-R200): Updated the logic to use the `which` crate for locating the `dash-qt` executable in the …
=> feat: autodetect dash-qt binary location

src/ui/tokens/burn_tokens_screen.rs, src/ui/tokens/destroy_frozen_funds_screen.rs, src/ui/tokens/freeze_tokens_screen.rs, src/ui/tokens/mint_tokens_screen.rs, src/ui/tokens/pause_tokens_screen.rs, src/ui/tokens/resume_tokens_screen.rs, src/ui/tokens/set_token_price_screen.rs, src/ui/tokens/unfreeze_tokens_screen.rs
Updated UI headings across multiple screens to enhance clarity and consistency regarding group actions. The changes ensure that headings accurately reflect the specific action being performed, particularly when initiated by a group. This improves user understanding of the action's context and outcome. 
Key changes include:
- Updated headings for group actions in burn, destroy, freeze, mint, pause, resume, set price, and unfreeze screens to specify the nature of the action.
- Ensured consistent messaging regarding unilateral group membership and the presence of a group.
=> feat: update group action headings for clarity and consistency

src/context.rs, src/ui/components/left_panel.rs, src/ui/contracts_documents/contracts_documents_screen.rs, src/ui/contracts_documents/register_contract_screen.rs, src/ui/contracts_documents/update_contract_screen.rs, src/ui/identities/transfer_screen.rs, src/ui/identities/withdraw_screen.rs, src/ui/network_chooser_screen.rs, src/ui/tokens/burn_tokens_screen.rs, src/ui/tokens/claim_tokens_screen.rs, src/ui/tokens/destroy_frozen_funds_screen.rs, src/ui/tokens/direct_token_purchase_screen.rs, src/ui/tokens/freeze_tokens_screen.rs, src/ui/tokens/mint_tokens_screen.rs, src/ui/tokens/pause_tokens_screen.rs, src/ui/tokens/resume_tokens_screen.rs, src/ui/tokens/set_token_price_screen.rs, src/ui/tokens/tokens_screen.rs, src/ui/tokens/transfer_tokens_screen.rs, src/ui/tokens/unfreeze_tokens_screen.rs, src/ui/tokens/update_token_config.rs
Add a toggle in settings screen to enable disable dev mode. Dev mode text at bottom left is clickable when dev mode is on. 
Disable token screens and group actions screens if network == mainnet (temporary while we are on testnet)
=> feat: dev mode toggle and disable screens for mainnet

src/app.rs, src/backend_task/register_contract.rs, src/backend_task/update_data_contract.rs, src/context.rs, src/database/asset_lock_transaction.rs, src/database/contracts.rs, src/database/identities.rs, src/database/initialization.rs, src/database/tokens.rs, src/ui/mod.rs, src/ui/tools/contract_visualizer_screen.rs, src/ui/tools/mod.rs
Updated the migration process for database version 9 to ensure all relevant data is deleted from Devnet and Regtest networks. This includes:
- Added methods to delete all asset lock transactions, contracts, and identities for Devnet and Regtest.
- Ensured these methods are called during the migration to prevent leftover data from previous versions.
- Improved error handling in the contract registration process to provide clearer messages.
This change is necessary to maintain data integrity and consistency during database migrations.
=> fix: fix migration process for database version 9

.gitignore, src/context.rs, src/database/contracts.rs, src/ui/tokens/transfer_tokens_screen.rs
- Added a new method `get_unqualified_contract_by_id` in the `Database` struct to fetch a `DataContract` based on its ID and network.
- Updated the `AppContext` to include a new method that calls the database method.
- Modified the `TransferTokensScreen` to use the new method for retrieving the data contract, simplifying the logic by directly fetching the contract instead of filtering a list. 
- Updated `.gitignore` to include `build-test/` directory.
=> feat: add method to retrieve unqualified contract by ID

src/backend_task/platform_info.rs
This pull request modifies the `format_withdrawal_documents_with_daily_limit` function in `src/backend_task/platform_info.rs` to improve error handling when converting a script to an address.
Error handling improvement:
* Updated the `Address::from_script` call to handle errors gracefully by using `.map()` to convert the address to a string and `.unwrap_or_else()` to return a formatted error message if the address conversion fails.
=> fix: panic when fetching withdrawals due to invalid destination address

Cargo.lock, Cargo.toml, src/model/wallet/mod.rs
This pull request implements correct debug logging of wallet seeds.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L21-R21): Updated the `dash-sdk` dependency to a newer Git revision (`5f93c70720a1ea09f91c9142668e17f314986f03`) for compatibility with the latest platform changes.
* [`src/model/wallet/mod.rs`](diffhunk://#diff-d267e65e0ac1c0008842ec1436746440180f41162845a0e8f14b9019187b2471L151-R166): Added a custom `Debug` implementation for `OpenKeyItem` to display a hashed representation of the seed, enhancing debugging clarity.
* [`src/model/wallet/mod.rs`](diffhunk://#diff-d267e65e0ac1c0008842ec1436746440180f41162845a0e8f14b9019187b2471L151-R166): Removed the `#[derive(Debug)]` attribute from `OpenKeyItem` and manually implemented the …
=> fix: correct format of open seed in logs

Cargo.toml
Whole project formats format strings like that:
```format!("foo bar {} {}", a, b)```
In Rust 1.88, it is considered code style issue and causes CI/CD to fail; however, we  don't want to change it everywhere, so we disable this check.
=> fix(build): allow uninlined format args in source code

src/ui/contracts_documents/document_action_screen.rs
This update modifies the `DocumentActionScreen` to skip processing of empty optional fields when the schema indicates that the field is not required. This change prevents unnecessary processing of empty inputs, improving the efficiency of the document action handling. The logic was added in two places within the `DocumentActionScreen` implementation where input values are processed.
=> feat: skip processing of empty optional fields in document actions

src/backend_task/tokens/mod.rs, src/ui/identities/top_up_identity_screen/by_wallet_qr_code.rs, src/ui/identities/top_up_identity_screen/mod.rs
There were a few issues.
It wasn't even displaying to begin with because of an early return.
Then it was automatically saying "No wallet selected"
Then the QR code wasn't working - it had Dash Core sending funds to itself.
=> fix: top up with qr code wasnt working

src/app.rs, src/context.rs, src/model/mod.rs, src/model/settings.rs, src/ui/components/dpns_subscreen_chooser_panel.rs, src/ui/components/tokens_subscreen_chooser_panel.rs, src/ui/components/tools_subscreen_chooser_panel.rs, src/ui/network_chooser_screen.rs
dash-qt path is not correctly autodetected
Refactored settings handling to make it easier to manage dash-qt path (and others).
This pull request refactors the handling of application settings by introducing a new `Settings` struct and centralizing its usage across the codebase. The changes simplify the code, improve readability, and enhance maintainability by replacing complex tuple-based settings with a structured approach. Additionally, redundant code for detecting the Dash-Qt binary path has been consolidated into the `Settings` struct.
* Introduced a new `Settings` struct in `src/model/settings.rs` to encapsulate application settings, replacing tuple-based settings. Includes methods for creating, converting, and defaulting settings, along with logic for Dash-Qt path detection.
* …
=> fix: dash-qt path autodetection fails

src/ui/identities/add_new_identity_screen/mod.rs, src/ui/identities/top_up_identity_screen/mod.rs
This pull request introduces changes to ensure proper state resets when switching wallets in the `AddNewIdentityScreen` and `TopUpIdentityScreen` components. The updates improve the user experience by resetting relevant fields and returning the interface to the initial step for selecting a funding method.
* [`src/ui/identities/add_new_identity_screen/mod.rs`](diffhunk://#diff-5fa5172ab2569a44b5b55b181bcf49177efa56b0f9c985fe23d26baa4bdaae3dR376-R386): Updated the `AddNewIdentityScreen` to reset `funding_address`, `funding_asset_lock`, `funding_utxo`, `copied_to_clipboard`, and set the step to `ChooseFundingMethod` when a new wallet is selected.
* [`src/ui/identities/top_up_identity_screen/mod.rs`](diffhunk://#diff-653578740fdf30123b18359e605ce6322651124e2f04ff18a2b343a1eb0f025cR120-R130): …
=> fix: change of wallet on top up does not update the address

src/backend_task/system_task/mod.rs, src/context.rs, src/database/settings.rs, src/ui/components/top_panel.rs, src/ui/network_chooser_screen.rs, src/ui/wallets/add_new_wallet_screen.rs, src/ui/wallets/import_wallet_screen.rs
Settings are read from DB a few times with every repaint of UI.
This pull request introduces a caching mechanism for application settings to improve performance and ensure atomic updates. The key changes include adding a settings cache to `AppContext`, implementing methods to manage the cache, and updating database interaction logic to integrate with the cache. Additionally, direct database calls in the UI layer have been replaced with `AppContext` methods to ensure proper cache handling.
* **Added a settings cache to `AppContext`:** Introduced a `RwLock`-protected `cached_settings` field to store settings and allow concurrent reads while ensuring exclusive writes during updates (`src/context.rs`, [[1]](diffhunk://#diff-d6346fd7d17270b1282142aeeda9c4bc2b7d8fd0f37b24a1c871a9257f0ed0aaR79-R8 …
=> fix: settings are read from db multiple times a second

src/backend_task/identity/load_identity.rs, src/backend_task/identity/load_identity_from_wallet.rs, src/backend_task/identity/register_identity.rs, src/backend_task/system_task/mod.rs, src/database/identities.rs, src/database/wallet.rs, src/model/qualified_identity/encrypted_key_storage.rs, src/model/qualified_identity/mod.rs, src/model/wallet/mod.rs, src/ui/identities/keys/key_info_screen.rs, src/ui/tokens/tokens_screen/mod.rs, src/ui/tokens/tokens_screen/my_tokens.rs
The main reason for this was that private keys were all exporting as if for mainnet.
Added a `network` field to various identity-related structures and methods to support network-specific operations. This change ensures that the network context is consistently passed through the application, enhancing the handling of identities across different networks. The updates include modifications to the `QualifiedIdentity`, database interactions, and wallet operations to accommodate the new field.
=> feat: add network field to identity structures

src/ui/identities/keys/key_info_screen.rs
This update adds the display of the private key in both Wallet Import Format (WIF) and Hex format on the Key Info screen. Labels have been added to clearly indicate each format, along with multiline text fields for user visibility. This enhancement improves the user experience by providing additional information about the private key in a more accessible manner.
=> feat: add display for private key in both WIF and Hex formats

src/ui/tokens/tokens_screen/mod.rs
Token Purchase button wouldn't render if a token price was set after the app was loaded. Had to clear the screen cache on refresh.
=> fix: token purchasability was not refreshing unless app restart
